### ISSUE TITLE
Testing on iPhone Xs Device causes a "Main Thread Checker" exception.

### ISSUE THREAD

**Issue by sedwo** [Swiftify-Corp/IHProgressHUD#3]
The moment I execute `IHProgressHUD.show(withStatus: "")`

I get a:
```
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 9428, TID: 3268605, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
```

https://developer.apple.com/documentation/code_diagnostics/main_thread_checker
fyi:  https://github.com/SVProgressHUD/SVProgressHUD/pull/822

**Comment by Ibrahimhass** [comment]
Hey @sedwo 
I tried this code snippet on iPhone XS Simulator Xcode version 10.0

`DispatchQueue.global(qos: .utility).async {
            IHProgressHUD.show(withStatus: "")
        }`

I am not able to reprduce the issue you reported. This is my log:

`2019-02-02 17:31:57.494634+0530 IHProgressHUD_Example[2599:101779] [framework] CUIThemeStore: No theme registered with id=0
Notification received: NSNotificationName(_rawValue: IHProgressHUDWillAppear)
Status user info key: Useful Information.
Notification received: NSNotificationName(_rawValue: IHProgressHUDDidAppear)
Status user info key: Useful Information.
Notification received: NSNotificationName(_rawValue: IHProgressHUDDidAppear)
Status user info key: Useful Information.
Notification received: NSNotificationName(_rawValue: IHProgressHUDWillDisappear)
Status user info key: Useful Information.
`

Also this was designed to be thread safe so I specifically checked for this issue. 

PS I am using the code from the example project here on github. Please let me know if I did miss on something or your suggestions as to how I can reproduce it. Thanks :)

**Comment by sedwo** [comment]
Hi @Ibrahimhass,
It doesn't trigger on the simulator, but on a real device.  I just happen to have the Xs model, but other models with iOS 12 might exhibit the same catch.

<img width="1680" alt="screen shot 2019-02-02 at 8 37 00 am" src="https://user-images.githubusercontent.com/1434449/52164837-cbbbb500-26c5-11e9-8e36-59e564bed202.png">

**Comment by Ibrahimhass** [comment]
Hey @sedwo 

I tested it on physical devices ie.
1. iPhone 7 (iOS 12.1)
2. iPad Model **MP2F2HN/A** running iOS 11.4.1
3. iPad Model **MP2F2HN/A** running iOS 12.1.1

Also, interesting I found a similar issue posted [here](https://github.com/Instabug/Instabug-iOS/issues/298). Check this specific [comment](https://github.com/Instabug/Instabug-iOS/issues/298#issuecomment-444095871). It's bug in iOS 12.1 on iPhone XS only but it has been fixed in iOS 12.1.1  

Please do try checking with iOS 12.1.1 later when you upgrade.

**Comment by sedwo** [comment]
@Ibrahimhass I'm running v12.1.2 on iPhone Xs and it still occurs.  I'll leave it for now and disable the check in Xcode.

**Comment by leandrodestro** [comment]
Happened to me as well on my Xs physical device.

**Comment by sbrighiu** [comment]
Why dont we just make an option to disable the use of CoreMotion?
